# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_item_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='list_id',
        ),
    ]
