# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20161003_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='list_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='owner',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
