# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20161006_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list_id',
            new_name='list',
        ),
    ]
