# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20161015_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
