# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import list.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20161016_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=list.models.item_image_path),
        ),
    ]
