# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20161030_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='share_id',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
