# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_list_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='share_id',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
