# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20161030_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='share_id',
            new_name='share',
        ),
    ]
