# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_auto_20161109_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
