# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
